CREATE ROLE game_app LOGIN PASSWORD '${GAME_APP_PASSWORD}';

GRANT CONNECT ON DATABASE game_progress_db_c1rr TO game_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO game_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO game_app;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO game_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO game_app;
